Add bundler/inline and install webrick locally to run tests
eradman/rset pull request #28
Opened 2023-08-01 23:33 UTC by zenspider

Closes #27

2023-08-01 23:39 UTC, zenspider commented
also happy to dress this up to work w/o bundler if webrick IS available (tho that'll be decreasing over time)

2023-08-02 00:11 UTC, eradman commented
Does Ruby ship with a simple HTTP server? I would prefer to use something built-in. I spent some time searching for a solution before, but didn't find any good answers.

2023-08-02 10:25 UTC, zenspider commented
It **_was_** webrick. First as part of the stdlib... then as a gem bundled. It got removed in a recent version of ruby... I think it is still considered the "defacto" web server for ruby because it is pure ruby and so well known... so I think flipping to bundler to pull it back in isn't the worst.

2023-08-02 12:59 UTC, eradman requested changes

2023-08-02 12:59 UTC, eradman commented on tests/test_rinstall.rb
> +ENV["GEM_HOME"] ||= "tmp"
Let's make this `.gem`

2023-08-02 12:59 UTC, eradman commented on input.c
> +			mkstemp(tmp_src);
Good. Unrelated, but since the directory is created locally this is correct.

2023-08-02 12:59 UTC, eradman commented on .gitignore
> +tests/tmp
tests/.gem

2023-08-30 00:07 UTC, merged